all:
	../../ESP32-LED/PCB/placeleds Roulette/Roulette.kicad_pcb -x100 -y100 -r50 --zone-in=1.25 --zone-out=1.25 --diode=1 --count=74 --vias=0.8 --power-vias=0.8 --angle=0 --fill=VLED --tracks
	../../ESP32-LED/PCB/placeleds Roulette/Roulette.kicad_pcb -x90 -y69 --rows=7 --cols=11 --diode=75 --cap=75 --vias=0.8 --power-vias=0.8 --angle=0 --fill=VLED --tracks

